version: '3'

tasks:
  templ:
    cmds:
      - templ generate --watch --proxy="http://localhost:8080" --open-browser=false
    silent: false

  server:
    cmds:
      - air --build.cmd "go build -o tmp/bin/main.exe ./cmd/server/main.go" --build.bin "tmp/bin/main.exe" --build.delay "100" --build.exclude_dir "node_modules" --build.include_ext "go" --build.stop_on_error "false" --misc.clean_on_exit true
    silent: false

  tailwind:
    cmds:
      - tailwindcss -i ./assets/css/input.css -o ./assets/css/output.css --watch
    silent: false

  dev:
    desc: "Run all watchers in parallel"
    cmds:
      - task templ &
      - task server &
      - task tailwind
    silent: false
  up:
    desc: "Run migrations up"
    cmds:
      - goose up
    silent: false
  reset:
    desc: "Run migrations down (reset)"
    cmds:
      - goose up
    silent: false
  gen:
    desc: "Generate go files from sqlc queries"
    cmds:
      - sqlc generate
    silent: false