// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID    uuid.UUID   `json:"id"`
	Title pgtype.Text `json:"title"`
	Body  pgtype.Text `json:"body"`
}
